Add falco-pubsub integration
falcosecurity/kubernetes-response-engine pull request #1
Opened 2019-02-27 10:54 UTC by tembleking

2019-03-14 11:46 UTC, nestorsalceda requested changes
That's a pretty good work! There are some rough edges that we need to address before merging. All the others integrations with the KRE allows to subscribe from a topic from multiple functions (Slack, Isolate ...) and uses wildcards for routing keys.

In the case of Google Pub/Sub we can send additional data, as the `falco.<severity>.<name>` and we need an adapter in the Google Function which reads the additional data and uses it as a routing key so that we can have 2 or 3 different functions subscribed to the same topic and when a message is fanned out and received for the 3 functions, they know if they have to process the message.

On the other hand, setting up a topic for each rule is a pretty tedious task. In the other deployments `cncf` and `aws` there is an automation for creating the required resources. We need the same here, we need to automate how the topic is created and cleaned and if we need more permissions, that should be also automated.

Thanks for the awesome work @tembleking !

2019-03-14 11:46 UTC, nestorsalceda commented on falco-pubsub/main.go
> +func adaptFromHelm(str string) string {
Please, rename to decodeFromSecret or similar. Helm is just a deployment automation tool.

2019-03-14 11:46 UTC, nestorsalceda commented on falco-pubsub/main.go
> +	topic := pubsubClient.Topic(googleTopicName)
Topic would be always the same.  With this approach we will need a topic for every falco rule to be subscribed.

Imagine the use case for sending **all** falco alerts to Slack and when a terminal shell is spawned in a pod, delete the pod. We want to be notified in slack about the terminal shell issue, and also we want to delete the pod automatically.

2019-03-14 11:46 UTC, nestorsalceda commented on playbooks/deploy_playbook_gke
> +directory="lambda"
Lambda is related to AWS. What do you think about calling it google-function or similar?

2019-03-14 11:46 UTC, nestorsalceda commented on playbooks/playbooks/__init__.py
> +    print(event)
Remove the print statement, please :)

2019-03-14 11:46 UTC, nestorsalceda commented on playbooks/playbooks/__init__.py
> +            except Exception as e:
Catch only `binascii.Error` or `TypeError`, which are the errors expected if we are trying to decode a base64 and is incorrectly padded.

2019-03-14 11:46 UTC, nestorsalceda commented on playbooks/playbooks/infrastructure.py
> +                            env=[
Do you think that will be possible to share the major part of the body and just change the env variables passed to the PodSpec instead of copy & pasting?

2019-03-14 11:46 UTC, nestorsalceda commented on playbooks/specs/playbooks/start_sysdig_capture_for_container_playbook_spec.py
> +with description(playbooks.StartSysdigCaptureForContainerS3) as self:
I miss the test for the `StartSysdigCaptureForContainerGcloud` scenario.

2019-03-14 11:46 UTC, nestorsalceda commented on sysdig-capturer/docker-entrypoint.sh
> +
Remove this whitespace, please :)

2019-03-14 11:46 UTC, nestorsalceda commented on falco-pubsub/Dockerfile
> +RUN strip falco-pubsub
I'm loving this multistage build, but I want to keep the different images consistent so please, add a `Makefile` honoring the `docker` target.

As long as you are using go modules, other targets will be become deprecated.

2019-03-14 11:46 UTC, nestorsalceda commented on playbooks/Pipfile
> +pyyaml = ">=3.13"
We need to keep the pyyaml version to 4.2.b1 due to security issues.

2019-03-14 11:46 UTC, nestorsalceda commented on playbooks/playbooks/__init__.py
> +                print(e)
Remove the print statement, please :)

2019-03-15 08:53 UTC, tembleking commented on playbooks/deploy_playbook_gke
> +directory="lambda"
Sure, we can change this. What name should we pick?

2019-03-15 08:55 UTC, tembleking commented on playbooks/playbooks/__init__.py
> +    print(event)
My mistake. Maybe next time I should not debug with print() :joy:

2019-03-15 08:55 UTC, tembleking commented on playbooks/playbooks/__init__.py
> +            except Exception as e:
Sure, makes more sense.

2019-03-15 09:00 UTC, tembleking commented on playbooks/playbooks/infrastructure.py
> +                            env=[
Good point, we can discuss about it.

2019-03-15 09:08 UTC, tembleking commented on playbooks/Pipfile
> +pyyaml = ">=3.13"
When I tried to deploy it, I had an error with this version in particular, so I rolled back to a previous stable version. The new stable version is 5.1. Do I change it back to 4.2.b1 or can we move a step forward towards 5.1?

2019-03-15 09:15 UTC, tembleking commented on falco-pubsub/main.go
> +func adaptFromHelm(str string) string {
Does this make more sense? I mean, this function is specifically created because Helm sends the secret in it's particular format, this is not a generic behavior.

2019-03-15 09:21 UTC, tembleking commented on falco-pubsub/main.go
> +	topic := pubsubClient.Topic(googleTopicName)
The idea behind this is that you deploy a function for a particular Falco event. When you create a function in Google Functions, you subscribe it to a Topic, the Topic is automatically created and this function gets subscribed to it. When Falco tries to send a message to a topic that doesn't work, it simply fails. We should talk about this.

2019-03-15 09:22 UTC, tembleking commented on playbooks/specs/playbooks/start_sysdig_capture_for_container_playbook_spec.py
> +with description(playbooks.StartSysdigCaptureForContainerS3) as self:
You are right, we need it!

2019-03-15 09:23 UTC, tembleking commented on falco-pubsub/Dockerfile
> +RUN strip falco-pubsub
I don't fully understand what you meant with keeping different images consistent. We should talk further about this.

2019-03-25 12:33 UTC, nestorsalceda commented on playbooks/playbooks/__init__.py
> +            except Exception as e:
Cool, right now we have to import binascii and logging

2019-04-05 10:25 UTC, nestorsalceda approved these changes

2019-04-05 10:25 UTC, merged

2019-04-05 10:25 UTC, nestorsalceda commented
Thank you very much @tembleking 

Great work!